name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
      - dev

env:
  VITE_MAPS_API_KEY: ${{secrets.MAPS_API_KEY_PROD}}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Firebase target
        id: set-target
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TARGET=prod" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "TARGET=dev" >> $GITHUB_ENV
          fi

      - run: npm ci && npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          target: ${{ env.TARGET }}
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRIPPLANNER_B05C6 }}
          channelId: live
          projectId: tripplanner-b05c6
